// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SCHQ_Blazor.Models;

#nullable disable

namespace SCHQ_Blazor.Migrations {
  [DbContext(typeof(RelationsContext))]
  [Migration("20241112074216_InitialMySQL")]
  partial class InitialMySQL {
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "8.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("SCHQ_Blazor.Models.Channel", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        b.Property<string>("AdminPassword")
            .HasColumnType("longtext")
            .UseCollation("NOCASE");

        b.Property<DateTime>("DateCreated")
            .HasColumnType("datetime(6)");

        b.Property<string>("Description")
            .HasColumnType("longtext")
            .UseCollation("NOCASE");

        b.Property<string>("Name")
            .HasColumnType("varchar(255)")
            .UseCollation("NOCASE");

        b.Property<string>("Password")
            .HasColumnType("longtext")
            .UseCollation("NOCASE");

        b.Property<int>("Permissions")
            .HasColumnType("int");

        b.Property<DateTime>("Timestamp")
            .HasColumnType("datetime(6)");

        b.HasKey("Id");

        b.HasIndex(new[] { "Name" }, "ChannelName")
            .IsUnique();

        b.ToTable("Channels");
      });

      modelBuilder.Entity("SCHQ_Blazor.Models.Relation", b => {
        b.Property<int>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnType("int");

        b.Property<int>("ChannelId")
            .HasColumnType("int");

        b.Property<string>("Comment")
            .HasColumnType("longtext")
            .UseCollation("NOCASE");

        b.Property<DateTime>("DateCreated")
            .HasColumnType("datetime(6)");

        b.Property<string>("Name")
            .HasColumnType("varchar(255)")
            .UseCollation("NOCASE");

        b.Property<DateTime>("Timestamp")
            .HasColumnType("datetime(6)");

        b.Property<int>("Type")
            .HasColumnType("int");

        b.Property<int>("UpdateCount")
            .HasColumnType("int");

        b.Property<int>("Value")
            .HasColumnType("int");

        b.HasKey("Id");

        b.HasIndex(new[] { "ChannelId", "Type", "Name" }, "RelationID")
            .IsUnique();

        b.ToTable("Relations");
      });

      modelBuilder.Entity("SCHQ_Blazor.Models.Relation", b => {
        b.HasOne("SCHQ_Blazor.Models.Channel", "Channel")
            .WithMany()
            .HasForeignKey("ChannelId")
            .OnDelete(DeleteBehavior.Cascade)
            .IsRequired();

        b.Navigation("Channel");
      });
#pragma warning restore 612, 618
    }
  }
}
