// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCHQ_Blazor.Models;

#nullable disable

namespace SCHQ_Blazor.Migrations
{
    [DbContext(typeof(RelationsContext))]
    partial class RelationsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RelationTag", b =>
                {
                    b.Property<int>("RelationId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("RelationId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RelationTag");
                });

            modelBuilder.Entity("SCHQ_Blazor.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdminPassword")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<string>("DiscordWebhookUrl")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .UseCollation("NOCASE");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<bool>("Private")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReadOnlyPassword")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "ChannelName")
                        .IsUnique();

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("SCHQ_Blazor.Models.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .UseCollation("NOCASE");

                    b.Property<string>("TagIds")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UpdateCount")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChannelId", "Type", "Name" }, "RelationID")
                        .IsUnique();

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("SCHQ_Blazor.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ChannelId")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .UseCollation("NOCASE");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(255)")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ChannelId", "Value" }, "ChannelTagIndex")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RelationTag", b =>
                {
                    b.HasOne("SCHQ_Blazor.Models.Relation", null)
                        .WithMany()
                        .HasForeignKey("RelationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCHQ_Blazor.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SCHQ_Blazor.Models.Relation", b =>
                {
                    b.HasOne("SCHQ_Blazor.Models.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("SCHQ_Blazor.Models.Tag", b =>
                {
                    b.HasOne("SCHQ_Blazor.Models.Channel", null)
                        .WithMany("Tags")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SCHQ_Blazor.Models.Channel", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
